markdown: kramdown
pygments: true
safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: 闭门造轮子
host: mytharcher.github.com
desc: 造轮子工程师的代码笔记

custom:
    category:
        thinking: 闭门思考
        problems: 问题记录
        knowledge: 知识经验
        discovery: 日新月异
    categories:
      - name:  thinking
        title: 闭门思考

      - name:  problems
        title: 问题记录

      - name:  knowledge
        title: 知识经验

      - name:  discovery
        title: 日新月异

meta:
    author:
        name: mytharcher
        email: mytharcher@example.com
        disqus: tech-justlog-me                     # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: mytharcher                          # GitHub账号
        gravatar: 1cd8c12591616d8c22aaa624f8c07834  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
